---
- name: Update system
  dnf: name=* state=latest
  sudo: yes

- name: Install prerequisites
  dnf: name={{ item }} state=present
  with_items:
    - vim
    - git
    - gcc
    - libffi-devel
    - openssl-devel
    - python-cffi
  sudo: yes
